### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by owen5mith** [runandrew/remix-wayf#1]
Hello,

Thanks for this great tool!

I've just gone to make a new group and am getting an "Application Error" (screenshot attached). Sadly I'm currently on a mobile device so can't provide a more detailed issue but will add the details when on a desktop device.

Best Wishes,
Owen

![Screenshot_20241103-111846.png](https://github.com/user-attachments/assets/28f7b3ae-0ba4-473b-a7aa-120136a0c0a3)

**Comment by runandrew** [comment]
@owen5mith Thanks for reporting. I looked into it this morning and found a couple issues.

1. The Supabase API key must have rotated at some point, updated that
2. Oddly the Vercel serverless functions were timing out, giving 504's (it was running fine locally). I found out I needed to instantiate the Supabase client during the function call. Credit to this issue: https://github.com/orgs/vercel/discussions/6994.

This should be resolved, please reach out if you continue to have issues.

**Comment by owen5mith** [comment]
Hey @runandrew , thank you for taking a look and fixing it so quickly!
